name: Ansible Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible and dependencies
      run: |
        sudo apt update
        sudo apt install -y ansible ansible-lint yamllint

    - name: Run yamllint on all YAML files
      run: |
        find . -name '*.yml' -print0 | while IFS= read -r -d '' file; do
          echo "Running yamllint on $file"
          yamllint "$file"
        done

    - name: Run ansible-lint on all YAML files
      run: |
        find . -name '*.yml' -print0 | while IFS= read -r -d '' file; do
          echo "Running ansible-lint on $file"
          ansible-lint "$file"
        done

    - name: Syntax check Ansible playbooks
      run: |
        find . -name '*.yml' -print0 | while IFS= read -r -d '' file; do
          echo "Running syntax check on Ansible playbook: $file"
          ansible-playbook --syntax-check "$file"
        done
