name: Ansible Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible and dependencies
      run: |
        sudo apt update
        sudo apt install -y ansible ansible-lint yamllint

    - name: Run yamllint
      run: yamllint audit_role/aaa_audit_playbook.yml

    - name: Run ansible-lint
      run: ansible-lint audit_role/aaa_audit_playbook.yml

    - name: Syntax check Ansible playbook
      run: ansible-playbook --syntax-check audit_role/aaa_audit_playbook.yml
